version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  name: react-app-build
  discard-paths: no
  base-directory: build  
  acl: bucket-owner-full-control